// Environment file generation utilities

import { getRpcPort, getPoolConfig, DEFAULT_AUTHORITY_PUBLIC_KEY, DEFAULT_CONFIG_VALUES } from '../../config-templates';

/**
 * Helper function to wrap address in addr(...) format if not already wrapped
 */
const wrapAddressInAddr = (address: string): string => {
  if (!address) return 'addr(bc1q...)';
  // Check if already wrapped
  if (address.startsWith('addr(') && address.endsWith(')')) {
    return address;
  }
  return `addr(${address})`;
};

/**
 * Generate docker_env file content for full-stack JD deployment
 */
export const generateEnvFile = (data: any, socketPath: string): string => {
  const network = (data?.selectedNetwork || "mainnet") as 'mainnet' | 'testnet4' | 'signet';
  const coreRpcPort = getRpcPort(network);
  const selectedPoolConfig = getPoolConfig(data?.selectedPool, network);
  // Use pool's authority pubkey if available, otherwise default
  const authorityPubkey = selectedPoolConfig?.authorityPubkey || DEFAULT_AUTHORITY_PUBLIC_KEY;
  const constructTemplates = data?.constructTemplates !== false;
  
  // Get network-specific address placeholder
  const addressPlaceholder = network === "testnet4" ? "tb1q..." : network === "signet" ? "bc1q..." : "bc1q...";
  
  let envContent = `# Stratum V2 Full Stack Deployment Environment Variables
# Generated by SRI Deployment Wizard
# Place this file in sv2-apps/docker/docker_env

# Pool Configuration
POOL_COINBASE_REWARD_SCRIPT=${wrapAddressInAddr(data?.poolPayoutAddress || addressPlaceholder)}
POOL_SIGNATURE=${data?.poolSignature || 'Stratum V2 SRI Pool'}
POOL_SHARE_BATCH_SIZE=${data?.shareBatchSize || 10}
POOL_SHARES_PER_MINUTE=${data?.sharesPerMinute || 6.0}
POOL_FEE_THRESHOLD=${data?.feeThreshold || 100}
POOL_MIN_INTERVAL=${data?.minInterval || 5}
`;

  // Only include JDS and JDC configs if constructing templates
  if (constructTemplates) {
    envContent += `
# JD Server Configuration
JDS_COINBASE_REWARD_SCRIPT=${wrapAddressInAddr(data?.poolPayoutAddress || addressPlaceholder)}
JDS_CORE_RPC_PORT=${coreRpcPort}
JDS_CORE_RPC_USER=${data?.coreRpcUser || 'username'}
JDS_CORE_RPC_PASS=${data?.coreRpcPass || 'password'}

# JD Client Configuration
JDC_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
JDC_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
JDC_SHARE_BATCH_SIZE=${data?.clientShareBatchSize || 10}
JDC_SIGNATURE=${data?.jdcSignature || 'Sv2MinerSignature'}
JDC_COINBASE_REWARD_SCRIPT=${wrapAddressInAddr(data?.coinbaseRewardScript || addressPlaceholder)}
JDC_FEE_THRESHOLD=${data?.clientFeeThreshold || 100}
JDC_MIN_INTERVAL=${data?.clientMinInterval || 5}
JDC_UPSTREAM_AUTHORITY_PUBKEY=${authorityPubkey}
JDC_POOL_ADDRESS=172.28.0.11
JDC_POOL_PORT=${DEFAULT_CONFIG_VALUES.poolPort}
JDC_UPSTREAM_JDS_ADDRESS=172.28.0.12
JDC_UPSTREAM_JDS_PORT=${DEFAULT_CONFIG_VALUES.jdsPort}
`;
  }

  envContent += `
# Translator Proxy Configuration
TPROXY_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
TPROXY_AGGREGATE_CHANNELS=${constructTemplates ? 'false' : 'true'}
TPROXY_MIN_INDIVIDUAL_MINER_HASHRATE=10_000_000_000_000.0
TPROXY_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
TPROXY_ENABLE_VARDIFF=${constructTemplates ? 'false' : 'true'}
TPROXY_UPSTREAM_ADDRESS=${constructTemplates ? '172.28.0.13' : '172.28.0.11'}
TPROXY_UPSTREAM_PORT=${constructTemplates ? DEFAULT_CONFIG_VALUES.jdcPort : DEFAULT_CONFIG_VALUES.poolPort}
TPROXY_UPSTREAM_AUTHORITY_PUBKEY=${data?.tproxyUpstreamAuthorityPubkey || authorityPubkey}

# Bitcoin Socket Path
BITCOIN_SOCKET_PATH=${socketPath}
`;

  return envContent;
};

/**
 * Generate docker_env file content for pool connection deployment
 */
export const generatePoolConnectionEnvFile = (data: any, socketPath?: string): string => {
  const needsSocketPath = !!socketPath;
  const network = (data?.selectedNetwork || "mainnet") as 'mainnet' | 'testnet4' | 'signet';
  const selectedPoolConfig = getPoolConfig(data?.selectedPool, network);
  // Use pool's authority pubkey if available, otherwise default
  const poolAuthorityPubkey = selectedPoolConfig?.authorityPubkey || DEFAULT_AUTHORITY_PUBLIC_KEY;
  
  let envContent = `# Stratum V2 Pool Connection Environment Variables
# Generated by SRI Deployment Wizard
# Place this file in sv2-apps/docker/docker_env

# Translator Proxy Configuration
TPROXY_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
TPROXY_AGGREGATE_CHANNELS=${selectedPoolConfig?.aggregateChannels ? 'true' : 'false'}
TPROXY_MIN_INDIVIDUAL_MINER_HASHRATE=10_000_000_000_000.0
TPROXY_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
TPROXY_ENABLE_VARDIFF=${needsSocketPath ? 'false' : 'true'}
TPROXY_UPSTREAM_ADDRESS=${needsSocketPath ? '172.28.0.13' : (selectedPoolConfig?.address || '127.0.0.1')}
TPROXY_UPSTREAM_PORT=${needsSocketPath ? DEFAULT_CONFIG_VALUES.jdcPort : (selectedPoolConfig?.port || DEFAULT_CONFIG_VALUES.poolPort)}
TPROXY_UPSTREAM_AUTHORITY_PUBKEY=${data?.tproxyUpstreamAuthorityPubkey || poolAuthorityPubkey}
`;

  if (needsSocketPath) {
    // Use pool's endpoints if available, otherwise fallback to docker IPs for local deployment
    const jdcPoolAddress = selectedPoolConfig?.address || '172.28.0.11';
    const jdcPoolPort = selectedPoolConfig?.port || DEFAULT_CONFIG_VALUES.poolPort;
    const jdcJdsAddress = selectedPoolConfig?.jdsAddress || '172.28.0.12';
    const jdcJdsPort = selectedPoolConfig?.jdsPort || DEFAULT_CONFIG_VALUES.jdsPort;
    
    envContent += `
# JD Client Configuration (for custom templates)
JDC_USER_IDENTITY=${data?.userIdentity || 'your_username_here'}
JDC_SHARES_PER_MINUTE=${data?.clientSharesPerMinute || 6.0}
JDC_SHARE_BATCH_SIZE=${data?.clientShareBatchSize || 10}
JDC_SIGNATURE=${data?.jdcSignature || 'Sv2MinerSignature'}
JDC_COINBASE_REWARD_SCRIPT=${wrapAddressInAddr(data?.coinbaseRewardScript || 'bc1q...')}
JDC_FEE_THRESHOLD=${data?.clientFeeThreshold || 100}
JDC_MIN_INTERVAL=${data?.clientMinInterval || 5}
JDC_UPSTREAM_AUTHORITY_PUBKEY=${poolAuthorityPubkey}
JDC_POOL_ADDRESS=${jdcPoolAddress}
JDC_POOL_PORT=${jdcPoolPort}
JDC_UPSTREAM_JDS_ADDRESS=${jdcJdsAddress}
JDC_UPSTREAM_JDS_PORT=${jdcJdsPort}

# Bitcoin Socket Path
BITCOIN_SOCKET_PATH=${socketPath}
`;
  } else {
    envContent += `
# Bitcoin Socket Path (not needed for tproxy-only, set to /dev/null)
BITCOIN_SOCKET_PATH=/dev/null
`;
  }
  
  return envContent;
};

